development: &generic
  mem_limit: 128M
  enable_star: 1
  min_infix_len: 3
  morphology: stem_enru
  charset_table: "0..9, A..Z->a..z, _, @, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451, U+451"
  max_matches: 100000
  per_page: 100000

  charset_type: "utf-8"
  expand_keywords: 1

production:
  <<: *generic